###########
# site.title

title:    'Three Bet'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

markdown: kramdown
kramdown:
  math_engine: mathjax

exclude:
- README.md
- LICENSE.md
